---
- name: Create SSL folder for nginx
  command: mkdir -p /etc/nginx/ssl

- name: Create self-signed SSL cert
  command: openssl req -new -nodes -x509 -subj "/C=ES/ST=Barcelona/L=Barcelona/O=IT/CN=${{www_domain}}" -days 3650 -keyout /etc/nginx/ssl/ssl_certificate.key -out /etc/nginx/ssl/ssl_certificate.crt -extensions v3_ca creates=/etc/nginx/ssl/ssl_certificate.crt