symfony_training.hello_world:
    path: /hello-world
    controller: App\Controller\HelloWorldController::salute

symfony_training.calculator.show_form:
    path: /calculator
    methods: [GET]
    controller: App\Controller\Calculator\ShowForm2Controller::showForm

symfony_training.calculator.calculate:
    path: /calculator
    methods: [POST]
    controller: App\Controller\Calculator\CalculateController::calculate