---

- name: Create www-data group
  group: name=www-data

- name: Create www-data user
  user: name=www-data group=www-data createhome=no

- name: Install Nginx
  apt: name=nginx-full={{nginx_version}}

- name: Add site virtual host
  template: src=vhost.conf.j2 dest=/etc/nginx/sites-available/default
  notify: restart nginx

- name: NGINX | Starting NGINX
  service:
    name: nginx
    state: started

- name: Use configured user
  lineinfile: dest=/etc/nginx/nginx.conf
              regexp='user (.*);'
              line='user {{ www_user }};'